# ==========================================
# POSTGRESQL CONFIGURATION
# ==========================================
app.datasource.postgres.url=jdbc:postgresql://dpg-d8r2c4ojs32c73bgakmg-a.singapore-postgres.render.com/lms_db_k1fx
app.datasource.postgres.username=root
app.datasource.postgres.password=20mkZcWq3K10y41MkG8kII26fMvG6i8m
app.datasource.postgres.driver-class-name=org.postgresql.Driver