# ==========================================
# 1. MYSQL CONFIGURATION (Custom Prefix)
# ==========================================
app.datasource.mysql.url=jdbc:mysql://localhost:3306/guvi_task
app.datasource.mysql.username=root
app.datasource.mysql.password=
app.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver