app:

spring:
  application:
    name: springbootmvc

  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update